submodels:
  - Capabilities Submodel: 
      - id: https://THU.de/_RA_Capabilities
      - elements :
          - Drill: Drill_Capability
          - MoveXY: MoveXY_Capability
          - SkillList : Supported_Skills
  - Interaction Submodel: 
      - id: https://THU.de/_RA_Interaction
      - elements :
          - Endpoints : _Endpoints
          - Machine OPC UA Endpoint: Machine_OPCUA_Endpoint
          - MQTT Broker Endpoint: MQTT_Broker_Endpoint
  - Knowledge Submodel: 
      - id: https://THU.de/_RA_Knowledge
      - elements :
          - Resource Constraints: _Resource_Constraints
          - Max Depth: MaxDepth
          - Max Depth Value : MaxDepthValue
          - Max Depth Unit : MaxDepthUnit
          - Max Depth Unit Short : MaxDepthUnitShort
          - Min Depth: MinDepth
          - Min Depth Value : MinDepthValue
          - Min Depth Unit : MinDepthUnit
          - Min Depth Unit Short : MinDepthUnitShort
          - Constraints Type: ContraintType
  - Operational State Submodel: 
      - id: https://THU.de/_RA_Operational_State
      - elements :
          - Current Operational Data : Current_Operational_State
          - Time Slots Operational Data: _TimeSlots_Operational_Data
          - Free Slots: Free_Slots
          - Booked Slots: Booked_Slots
          - Slot Duration : Slot_Duration
shell_id:
  - Resource Agent Shell : https://THU.de/ResourceAgent_
base_url: http://localhost:8081
machines:
  - Drill Machine 1: Drill_1
  - Drill Machine 2: Drill_2
